name: jpeg2000
description: Pure dart jpeg 2000
version: 1.0.0
homepage: https://github.com/insinfo/jpeg2000
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  meta: ^1.3.0
  
dev_dependencies:
  test: any

